# Generated by Django 3.1.3 on 2021-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_task_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='colour',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
