# Generated by Django 3.1.3 on 2021-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_event_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='colour',
            field=models.CharField(choices=[('White (default)', 'white'), ('Red', 'red'), ('Blue', 'blue'), ('Yellow', 'yellow'), ('Green', 'green'), ('Purple', 'purple'), ('Orange', 'orange'), ('Pink', 'pink')], max_length=15),
        ),
    ]
