# Generated by Django 3.1.3 on 2021-03-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_auto_20210315_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='colour',
        ),
    ]
